apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-app
  labels:
spec:
  selector:
    matchLabels:
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
    spec:
      containers:
        - name: app
          image: app-image:latest
          startupProbe:
            httpGet:
              path: /healthz
              port: 8000
            periodSeconds: 1
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8000
            periodSeconds: 3
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 100m      
